services:
  vps_lab:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: vps_lab
    ports:
      - "2222:22"
    volumes:
      - ../data:/data
      - ../scripts:/scripts/.
    working_dir: /scripts/.